language: go
go:
- 1.3
- 1.4
- tip

env:
  global:
  - KAFKA_INSTALL_ROOT=/home/travis/kafka KAFKA_HOSTNAME=localhost
  matrix:
  - KAFKA_VERSION=0.8.2.0
  - KAFKA_VERSION=0.8.1.1

before_install:
- export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}
- vagrant/install_cluster.sh
- vagrant/boot_cluster.sh
- vagrant/create_topics.sh
- go get golang.org/x/tools/cmd/vet
- go get github.com/kisielk/errcheck

script:
- go test -v -race ./...
- go vet ./...
- errcheck github.com/Shopify/sarama/
- if [[ -n $(go fmt ./...) ]]; then echo "Please run go fmt on your code." && exit 1; fi

notifications:
  flowdock: 15e08f7ed3a8fd2d89ddb36435301c1a

matrix:
  allow_failures:
    - go: tip

sudo: false
